---
- hosts: linux
  become: yes
  remote_user: ubuntu
  tasks:
  - name: Installing Zabbix *.deb format repository
    get_url:
      url: "https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb"
      dest: /home/ubuntu/
  - name: Dpkg Installed Zabbix repository
    apt:
      upgrade: dist
      update_cache: yes
      dpkg_options: "zabbix-release_5.0-1+focal_all.deb"
  - name: Install Zabbix Agent
    apt:
      update_cache: yes
      name: zabbix-agent
