version: '3.7'
services:
  dashboard:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
    - grafana_data:/var/lib/grafana
volumes:
  grafana_data:
